In [44]:
import numpy as np
nx = 2
ny = 3
nz = 4
N = nx * ny * nz
def convert_index(ix, iy, iz):
    return (ix + nx * (iy + iz * ny))

In [51]:
def back_con(j):
    iz = (j//nx)//ny
    iy = j//nx - ny * iz
    ix = j - nx * (iy + iz * ny)
    return np.array([ix, iy, iz]

In [46]:
for j in range(N):
    print(j, back_con(j))

0 (0, 0, 0)
1 (1, 0, 0)
2 (0, 1, 0)
3 (1, 1, 0)
4 (0, 2, 0)
5 (1, 2, 0)
6 (0, 0, 1)
7 (1, 0, 1)
8 (0, 1, 1)
9 (1, 1, 1)
10 (0, 2, 1)
11 (1, 2, 1)
12 (0, 0, 2)
13 (1, 0, 2)
14 (0, 1, 2)
15 (1, 1, 2)
16 (0, 2, 2)
17 (1, 2, 2)
18 (0, 0, 3)
19 (1, 0, 3)
20 (0, 1, 3)
21 (1, 1, 3)
22 (0, 2, 3)
23 (1, 2, 3)


In [53]:
print(back_con(np.array([1, 2, 3])))

[[1 0 1]
 [0 1 1]
 [0 0 0]]


In [40]:
for iz in range(nz):
    for iy in range(ny):
        for ix in range(nx):
            print(convert_index(ix, iy, iz), '(', ix, iy, iz, ')', back_con(convert_index(ix, iy, iz)))

0 ( 0 0 0 ) (0, 0, 0)
1 ( 1 0 0 ) (1, 0, 0)
2 ( 0 1 0 ) (0, 1, 0)
3 ( 1 1 0 ) (1, 1, 0)
4 ( 0 2 0 ) (0, 2, 0)
5 ( 1 2 0 ) (1, 2, 0)
6 ( 0 0 1 ) (0, 0, 1)
7 ( 1 0 1 ) (1, 0, 1)
8 ( 0 1 1 ) (0, 1, 1)
9 ( 1 1 1 ) (1, 1, 1)
10 ( 0 2 1 ) (0, 2, 1)
11 ( 1 2 1 ) (1, 2, 1)
12 ( 0 0 2 ) (0, 0, 2)
13 ( 1 0 2 ) (1, 0, 2)
14 ( 0 1 2 ) (0, 1, 2)
15 ( 1 1 2 ) (1, 1, 2)
16 ( 0 2 2 ) (0, 2, 2)
17 ( 1 2 2 ) (1, 2, 2)
18 ( 0 0 3 ) (0, 0, 3)
19 ( 1 0 3 ) (1, 0, 3)
20 ( 0 1 3 ) (0, 1, 3)
21 ( 1 1 3 ) (1, 1, 3)
22 ( 0 2 3 ) (0, 2, 3)
23 ( 1 2 3 ) (1, 2, 3)
